include(FetchContent)

set(ASSIMP_BUILD_TESTS                OFF CACHE INTERNAL "")
set(ASSIMP_INSTALL                    OFF CACHE INTERNAL "")
set(ASSIMP_INJECT_DEBUG_POSTFIX       OFF CACHE INTERNAL "")
set(ASSIMP_BUILD_SAMPLES              OFF CACHE INTERNAL "")
set(ASSIMP_BUILD_ASSIMP_TOOLS         OFF CACHE INTERNAL "")
set(ASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT OFF CACHE INTERNAL "")
set(ASSIMP_BUILD_OBJ_IMPORTER         ON  CACHE INTERNAL "")
set(ASSIMP_BUILD_FBX_IMPORTER         ON  CACHE INTERNAL "")
set(ASSIMP_BUILD_GLTF_IMPORTER        ON  CACHE INTERNAL "")

if(EMSCRIPTEN)
    set(ASSIMP_BUILD_ZLIB          ON  CACHE INTERNAL "")
    set(ASSIMP_WARNINGS_AS_ERRORS  OFF CACHE INTERNAL "")
    set(BUILD_SHARED_LIBS          OFF CACHE INTERNAL "") # must be static for WASM
endif()

FetchContent_Declare(
    assimp
    GIT_REPOSITORY https://github.com/assimp/assimp
    GIT_TAG        v6.0.4
)

FetchContent_MakeAvailable(assimp)